// Generated by dojo-bindgen on Sat, 24 May 2025 18:37:35 +0000. Do not modify this file manually.
import { Account } from "starknet";
import {
    Clause,
    Client,
    ModelClause,
    createClient,
    valueToToriiValueAndOperator,
} from "@dojoengine/torii-client";
import {
    LOCAL_KATANA,
    LOCAL_RELAY,
    LOCAL_TORII,
    createManifestFromJson,
} from "@dojoengine/core";

// Type definition for `dojo::meta::introspect::Struct` struct
export interface Struct {
    name: string;
    attrs: string[];
    children: Member[];
}

// Type definition for `inkfinity::models::Artist` struct
export interface Artist {
    artist: string;
    collected_fees: U256;
    amount_nft: U256;
    nft_sells: U256;
    ranking: number;
    collection: string;
    description: string;
    tags: string;
}

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: string[];
    pending_word: string;
    pending_word_len: number;
}

// Type definition for `dojo::meta::introspect::Enum` struct
export interface Enum {
    name: string;
    attrs: string[];
    children: [string, Ty][];
}

// Type definition for `inkfinity::models::ArtistValue` struct
export interface ArtistValue {
    collected_fees: U256;
    amount_nft: U256;
    nft_sells: U256;
    ranking: number;
    collection: string;
    description: string;
    tags: string;
}

// Type definition for `dojo::meta::introspect::Member` struct
export interface Member {
    name: string;
    attrs: string[];
    ty: Ty;
}

// Type definition for `dojo::meta::layout::FieldLayout` struct
export interface FieldLayout {
    selector: string;
    layout: Layout;
}

// Type definition for `core::integer::u256` struct
export interface U256 {
    low: bigint;
    high: bigint;
}

// Type definition for `dojo::model::definition::ModelDef` struct
export interface ModelDef {
    name: string;
    layout: Layout;
    schema: Struct;
    packed_size: Option<number>;
    unpacked_size: Option<number>;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
type Option<A> = { type: 'Some'; data: A; } | { type: 'None'; }
// Type definition for `dojo::meta::introspect::Ty` enum
type Ty = { type: 'Primitive'; data: string; } | { type: 'Struct'; data: Struct; } | { type: 'Enum'; data: Enum; } | { type: 'Tuple'; data: Ty[]; } | { type: 'Array'; data: Ty[]; } | { type: 'ByteArray'; }
// Type definition for `dojo::meta::layout::Layout` enum
type Layout = { type: 'Fixed'; data: number[]; } | { type: 'Struct'; data: FieldLayout[]; } | { type: 'Tuple'; data: Layout[]; } | { type: 'Array'; data: Layout[]; } | { type: 'ByteArray'; } | { type: 'Enum'; data: FieldLayout[]; }

// Type definition for `inkfinity::models::TattooValue` struct
export interface TattooValue {
    owner: string;
    price: U256;
}

// Type definition for `inkfinity::models::Tattoo` struct
export interface Tattoo {
    token_id: U256;
    artist: string;
    collection: string;
    owner: string;
    price: U256;
}


// Type definition for `inkfinity::models::User` struct
export interface User {
    user: string;
    amount_nft: U256;
    nft_sells: U256;
}

// Type definition for `inkfinity::models::UserValue` struct
export interface UserValue {
    amount_nft: U256;
    nft_sells: U256;
}


class BaseCalls {
    contractAddress: string;
    account?: Account;

    constructor(contractAddress: string, account?: Account) {
        this.account = account;
        this.contractAddress = contractAddress;
    }

    async execute(entrypoint: string, calldata: any[] = []): Promise<void> {
        if (!this.account) {
            throw new Error("No account set to interact with dojo_starter");
        }

        await this.account.execute(
            {
                contractAddress: this.contractAddress,
                entrypoint,
                calldata,
            },
            undefined,
            {
                maxFee: 0,
            }
        );
    }
}

class ActionsCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async upgrade(new_class_hash: string): Promise<void> {
        try {
            await this.execute("upgrade", [new_class_hash])
        } catch (error) {
            console.error("Error executing upgrade:", error);
            throw error;
        }
    }

    async dojoName(): Promise<void> {
        try {
            await this.execute("dojo_name", [])
        } catch (error) {
            console.error("Error executing dojoName:", error);
            throw error;
        }
    }

    async worldDispatcher(): Promise<void> {
        try {
            await this.execute("world_dispatcher", [])
        } catch (error) {
            console.error("Error executing worldDispatcher:", error);
            throw error;
        }
    }

    async mint(token_id: U256, uri: string, price: U256, collection: string): Promise<void> {
        try {
            await this.execute("mint", [props.token_id.low,
                    props.token_id.high,
                props.uri.data,
                    props.uri.pending_word,
                    props.uri.pending_word_len,
                props.price.low,
                    props.price.high,
                collection])
        } catch (error) {
            console.error("Error executing mint:", error);
            throw error;
        }
    }

    async invest(amount: U256): Promise<void> {
        try {
            await this.execute("invest", [props.amount.low,
                    props.amount.high])
        } catch (error) {
            console.error("Error executing invest:", error);
            throw error;
        }
    }

    async createDrop(): Promise<void> {
        try {
            await this.execute("create_drop", [])
        } catch (error) {
            console.error("Error executing createDrop:", error);
            throw error;
        }
    }

    async buy(token_id: U256): Promise<void> {
        try {
            await this.execute("buy", [props.token_id.low,
                    props.token_id.high])
        } catch (error) {
            console.error("Error executing buy:", error);
            throw error;
        }
    }

    async list(token_id: U256, price: U256): Promise<void> {
        try {
            await this.execute("list", [props.token_id.low,
                    props.token_id.high,
                props.price.low,
                    props.price.high])
        } catch (error) {
            console.error("Error executing list:", error);
            throw error;
        }
    }

    async changeOwner(token_id: U256, new_owner: string): Promise<void> {
        try {
            await this.execute("change_owner", [props.token_id.low,
                    props.token_id.high,
                new_owner])
        } catch (error) {
            console.error("Error executing changeOwner:", error);
            throw error;
        }
    }

    async changePrice(token_id: U256, price: U256): Promise<void> {
        try {
            await this.execute("change_price", [props.token_id.low,
                    props.token_id.high,
                props.price.low,
                    props.price.high])
        } catch (error) {
            console.error("Error executing changePrice:", error);
            throw error;
        }
    }
}

type Query = Partial<{
    Artist: ModelClause<Artist>;
    Tattoo: ModelClause<Tattoo>;
    User: ModelClause<User>;
}>;

type ResultMapping = {
    Artist: Artist;
    Tattoo: Tattoo;
    User: User;
};

type QueryResult<T extends Query> = {
    [K in keyof T]: K extends keyof ResultMapping ? ResultMapping[K] : never;
};

// Only supports a single model for now, since torii doesn't support multiple models
// And inside that single model, there's only support for a single query.
function convertQueryToToriiClause(query: Query): Clause | undefined {
    const [model, clause] = Object.entries(query)[0];

    if (Object.keys(clause).length === 0) {
        return undefined;
    }

    const clauses: Clause[] = Object.entries(clause).map(([key, value]) => {
        return {
            Member: {
                model,
                member: key,
                ...valueToToriiValueAndOperator(value),
            },
        } satisfies Clause;
    });

    return clauses[0];
}
type GeneralParams = {
    toriiUrl?: string;
    relayUrl?: string;
    account?: Account;
};

type InitialParams = GeneralParams &
    (
        | {
                rpcUrl?: string;
                worldAddress: string;
                actionsAddress: string;
            }
        | {
                manifest: any;
            }
    );

export class Inkfinity {
    rpcUrl: string;
    toriiUrl: string;
    toriiPromise: Promise<Client>;
    relayUrl: string;
    worldAddress: string;
    private _account?: Account;
    actions: ActionsCalls;
    actionsAddress: string;

    constructor(params: InitialParams) {
        if ("manifest" in params) {
            const config = createManifestFromJson(params.manifest);
            this.rpcUrl = config.world.metadata.rpc_url;
            this.worldAddress = config.world.address;

            const actionsAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::actions::actions"
            )?.address;

            if (!actionsAddress) {
                throw new Error("No actions contract found in the manifest");
            }

            this.actionsAddress = actionsAddress;
        } else {
            this.rpcUrl = params.rpcUrl || LOCAL_KATANA;
            this.worldAddress = params.worldAddress;
            this.actionsAddress = params.actionsAddress;
        }
        this.toriiUrl = params.toriiUrl || LOCAL_TORII;
        this.relayUrl = params.relayUrl || LOCAL_RELAY;
        this._account = params.account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);

        this.toriiPromise = createClient([], {
            rpcUrl: this.rpcUrl,
            toriiUrl: this.toriiUrl,
            worldAddress: this.worldAddress,
            relayUrl: this.relayUrl,
        });
    }

    get account(): Account | undefined {
        return this._account;
    }

    set account(account: Account) {
        this._account = account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);
    }

    async query<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        return {
            torii,
            findEntities: async () => this.findEntities(query, limit, offset),
        };
    }

    async findEntities<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        const clause = convertQueryToToriiClause(query);

        const toriiResult = await torii.getEntities({
            limit,
            offset,
            clause,
        });

        return toriiResult as Record<string, QueryResult<T>>;
    }

    async findEntity<T extends Query>(query: T) {
        const result = await this.findEntities(query, 1);

        if (Object.values(result).length === 0) {
            return undefined;
        }

        return Object.values(result)[0] as QueryResult<T>;
    }
}